ERROR 2025-08-06 22:49:46,058 log 40592 3832 Internal Server Error: /auth/profile/complete/
Traceback (most recent call last):
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\core\views.py", line 680, in profile_completion_view
    return render(request, 'core/profile_completion.html', context)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Local Disk E\BlitzTech Systems\erpdev\venv\lib\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
